services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: codely
      POSTGRES_PASSWORD: c0d3ly7v
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./databases:/docker-entrypoint-initdb.d

volumes:
  db_data:
